# Data Lakes with Spark

In [116]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import udf, col, monotonically_increasing_id
from pyspark.sql.functions import year, month, dayofmonth, hour, weekofyear, date_format
from pyspark.sql.types import IntegerType, StringType, TimestampType, DateType, DatetimeConverter
from datetime import datetime

In [3]:
spark = SparkSession.builder.config("spark.jars.packages", "org.apache.hadoop:hadoop-aws:2.7.0").getOrCreate()

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/Users/alfredo.leon/opt/miniconda3/envs/SparkifyDataLakes/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

:: loading settings :: url = jar:file:/Users/alfredo.leon/opt/miniconda3/envs/SparkifyDataLakes/lib/python3.7/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml

Ivy Default Cache set to: /Users/alfredo.leon/.ivy2/cache
The jars for the packages stored in: /Users/alfredo.leon/.ivy2/jars
org.apache.hadoop#hadoop-aws added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-f9647eea-c67e-4203-a5fa-ab641bcec7a2;1.0
	confs: [default]
	found org.apache.hadoop#hadoop-aws;2.7.0 in central
	found org.apache.hadoop#hadoop-common;2.7.0 in central
	found org.apache.hadoop#hadoop-annotations;2.7.0 in central
	found com.google.guava#guava;11.0.2 in central
	found com.google.code.findbugs#jsr305;3.0.0 in central
	found commons-cli#commons-cli;1.2 in central
	found org.apache.commons#commons-math3;3.1.1 in central
	found xmlenc#xmlenc;0.52 in central
	found commons-httpclient#commons-httpclient;3.1 in central
	found commons-logging#commons-logging;1.1.3 in central
	found commons-codec#commons-codec;1.4 in central
	found commons-io#commons-io;2.4 in central
	found commons-net#commons-net;3.1 in central
	found commons-collections#commons-collections;3.2.1 in central
	found javax.servlet#servlet-api;2.5 in central
	found org.mortbay.jetty#jetty;6.1.26 in central
	found org.mortbay.jetty#jetty-util;6.1.26 in central
	found com.sun.jersey#jersey-core;1.9 in central
	found com.sun.jersey#jersey-json;1.9 in central
	found org.codehaus.jettison#jettison;1.1 in central
	found com.sun.xml.bind#jaxb-impl;2.2.3-1 in central
	found javax.xml.bind#jaxb-api;2.2.2 in central
	found javax.xml.stream#stax-api;1.0-2 in central
	found javax.activation#activation;1.1 in central
	found org.codehaus.jackson#jackson-core-asl;1.9.13 in central
	found org.codehaus.jackson#jackson-mapper-asl;1.9.13 in central
	found org.codehaus.jackson#jackson-jaxrs;1.9.13 in central
	found org.codehaus.jackson#jackson-xc;1.9.13 in central
	found com.sun.jersey#jersey-server;1.9 in central
	found asm#asm;3.2 in central
	found log4j#log4j;1.2.17 in central
	found net.java.dev.jets3t#jets3t;0.9.0 in central
	found org.apache.httpcomponents#httpclient;4.2.5 in central
	found org.apache.httpcomponents#httpcore;4.2.5 in central
	found com.jamesmurty.utils#java-xmlbuilder;0.4 in central
	found commons-lang#commons-lang;2.6 in central
	found commons-configuration#commons-configuration;1.6 in central
	found commons-digester#commons-digester;1.8 in central
	found commons-beanutils#commons-beanutils;1.7.0 in central
	found commons-beanutils#commons-beanutils-core;1.8.0 in central
	found org.slf4j#slf4j-api;1.7.10 in central
	found org.apache.avro#avro;1.7.4 in central
	found com.thoughtworks.paranamer#paranamer;2.3 in central
	found org.xerial.snappy#snappy-java;1.0.4.1 in central
	found org.apache.commons#commons-compress;1.4.1 in central
	found org.tukaani#xz;1.0 in central
	found com.google.protobuf#protobuf-java;2.5.0 in central
	found com.google.code.gson#gson;2.2.4 in central
	found org.apache.hadoop#hadoop-auth;2.7.0 in central
	found org.apache.directory.server#apacheds-kerberos-codec;2.0.0-M15 in central
	found org.apache.directory.server#apacheds-i18n;2.0.0-M15 in central
	found org.apache.directory.api#api-asn1-api;1.0.0-M20 in central
	found org.apache.directory.api#api-util;1.0.0-M20 in central
	found org.apache.zookeeper#zookeeper;3.4.6 in central
	found org.slf4j#slf4j-log4j12;1.7.10 in central
	found io.netty#netty;3.6.2.Final in central
	found org.apache.curator#curator-framework;2.7.1 in central
	found org.apache.curator#curator-client;2.7.1 in central
	found com.jcraft#jsch;0.1.42 in central
	found org.apache.curator#curator-recipes;2.7.1 in central
	found org.apache.htrace#htrace-core;3.1.0-incubating in central
	found javax.servlet.jsp#jsp-api;2.1 in central
	found jline#jline;0.9.94 in central
	found junit#junit;4.11 in central
	found org.hamcrest#hamcrest-core;1.3 in central
	found com.fasterxml.jackson.core#jackson-databind;2.2.3 in central
	found com.fasterxml.jackson.core#jackson-annotations;2.2.3 in central
	found com.fasterxml.jackson.core#jackson-core;2.2.3 in central
	found com.amazonaws#aws-java-sdk;1.7.4 in central
	found joda-time#joda-time;2.10.13 in central
	[2.10.13] joda-time#joda-time;[2.2,)
downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.0/hadoop-aws-2.7.0.jar ...
	[SUCCESSFUL ] org.apache.hadoop#hadoop-aws;2.7.0!hadoop-aws.jar (130ms)
downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/2.7.0/hadoop-common-2.7.0.jar ...
	[SUCCESSFUL ] org.apache.hadoop#hadoop-common;2.7.0!hadoop-common.jar (959ms)
downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.2.3/jackson-databind-2.2.3.jar ...
	[SUCCESSFUL ] com.fasterxml.jackson.core#jackson-databind;2.2.3!jackson-databind.jar (191ms)
downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.2.3/jackson-annotations-2.2.3.jar ...
	[SUCCESSFUL ] com.fasterxml.jackson.core#jackson-annotations;2.2.3!jackson-annotations.jar (62ms)
downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.7.4/aws-java-sdk-1.7.4.jar ...
	[SUCCESSFUL ] com.amazonaws#aws-java-sdk;1.7.4!aws-java-sdk.jar (2812ms)
downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-annotations/2.7.0/hadoop-annotations-2.7.0.jar ...
	[SUCCESSFUL ] org.apache.hadoop#hadoop-annotations;2.7.0!hadoop-annotations.jar (81ms)
downloading https://repo1.maven.org/maven2/com/google/guava/guava/11.0.2/guava-11.0.2.jar ...
	[SUCCESSFUL ] com.google.guava#guava;11.0.2!guava.jar (569ms)
downloading https://repo1.maven.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.jar ...
	[SUCCESSFUL ] commons-cli#commons-cli;1.2!commons-cli.jar (59ms)
downloading https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.1.1/commons-math3-3.1.1.jar ...
	[SUCCESSFUL ] org.apache.commons#commons-math3;3.1.1!commons-math3.jar (467ms)
downloading https://repo1.maven.org/maven2/xmlenc/xmlenc/0.52/xmlenc-0.52.jar ...
	[SUCCESSFUL ] xmlenc#xmlenc;0.52!xmlenc.jar (52ms)
downloading https://repo1.maven.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar ...
	[SUCCESSFUL ] commons-httpclient#commons-httpclient;3.1!commons-httpclient.jar (120ms)
downloading https://repo1.maven.org/maven2/commons-codec/commons-codec/1.4/commons-codec-1.4.jar ...
	[SUCCESSFUL ] commons-codec#commons-codec;1.4!commons-codec.jar (61ms)
downloading https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar ...
	[SUCCESSFUL ] commons-io#commons-io;2.4!commons-io.jar (88ms)
downloading https://repo1.maven.org/maven2/commons-net/commons-net/3.1/commons-net-3.1.jar ...
	[SUCCESSFUL ] commons-net#commons-net;3.1!commons-net.jar (112ms)
downloading https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar ...
	[SUCCESSFUL ] commons-collections#commons-collections;3.2.1!commons-collections.jar (180ms)
downloading https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar ...
	[SUCCESSFUL ] javax.servlet#servlet-api;2.5!servlet-api.jar (73ms)
downloading https://repo1.maven.org/maven2/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar ...
	[SUCCESSFUL ] org.mortbay.jetty#jetty;6.1.26!jetty.jar (175ms)
downloading https://repo1.maven.org/maven2/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar ...
	[SUCCESSFUL ] org.mortbay.jetty#jetty-util;6.1.26!jetty-util.jar (83ms)
downloading https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar ...
	[SUCCESSFUL ] com.sun.jersey#jersey-core;1.9!jersey-core.jar(bundle) (156ms)
downloading https://repo1.maven.org/maven2/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.jar ...
	[SUCCESSFUL ] com.sun.jersey#jersey-json;1.9!jersey-json.jar(bundle) (80ms)
downloading https://repo1.maven.org/maven2/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.jar ...
	[SUCCESSFUL ] com.sun.jersey#jersey-server;1.9!jersey-server.jar(bundle) (213ms)
downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
	[SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (63ms)
downloading https://repo1.maven.org/maven2/log4j/log4j/1.2.17/log4j-1.2.17.jar ...
	[SUCCESSFUL ] log4j#log4j;1.2.17!log4j.jar(bundle) (164ms)
downloading https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.0/jets3t-0.9.0.jar ...
	[SUCCESSFUL ] net.java.dev.jets3t#jets3t;0.9.0!jets3t.jar (175ms)
downloading https://repo1.maven.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar ...

	[SUCCESSFUL ] commons-lang#commons-lang;2.6!commons-lang.jar (112ms)
downloading https://repo1.maven.org/maven2/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar ...
	[SUCCESSFUL ] commons-configuration#commons-configuration;1.6!commons-configuration.jar (117ms)
downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar ...
	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.10!slf4j-api.jar (59ms)
downloading https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar ...
	[SUCCESSFUL ] org.codehaus.jackson#jackson-core-asl;1.9.13!jackson-core-asl.jar (108ms)
downloading https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar ...
	[SUCCESSFUL ] org.codehaus.jackson#jackson-mapper-asl;1.9.13!jackson-mapper-asl.jar (230ms)
downloading https://repo1.maven.org/maven2/org/apache/avro/avro/1.7.4/avro-1.7.4.jar ...
	[SUCCESSFUL ] org.apache.avro#avro;1.7.4!avro.jar (200ms)
downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar ...
	[SUCCESSFUL ] com.google.protobuf#protobuf-java;2.5.0!protobuf-java.jar(bundle) (173ms)
downloading https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar ...
	[SUCCESSFUL ] com.google.code.gson#gson;2.2.4!gson.jar (113ms)
downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-auth/2.7.0/hadoop-auth-2.7.0.jar ...
	[SUCCESSFUL ] org.apache.hadoop#hadoop-auth;2.7.0!hadoop-auth.jar (70ms)
downloading https://repo1.maven.org/maven2/com/jcraft/jsch/0.1.42/jsch-0.1.42.jar ...
	[SUCCESSFUL ] com.jcraft#jsch;0.1.42!jsch.jar (118ms)
downloading https://repo1.maven.org/maven2/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.jar ...
	[SUCCESSFUL ] org.apache.curator#curator-client;2.7.1!curator-client.jar(bundle) (67ms)
downloading https://repo1.maven.org/maven2/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.jar ...
	[SUCCESSFUL ] org.apache.curator#curator-recipes;2.7.1!curator-recipes.jar(bundle) (119ms)
downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
	[SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (69ms)
downloading https://repo1.maven.org/maven2/org/apache/htrace/htrace-core/3.1.0-incubating/htrace-core-3.1.0-incubating.jar ...
	[SUCCESSFUL ] org.apache.htrace#htrace-core;3.1.0-incubating!htrace-core.jar (389ms)
downloading https://repo1.maven.org/maven2/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar ...
	[SUCCESSFUL ] org.apache.zookeeper#zookeeper;3.4.6!zookeeper.jar (225ms)
downloading https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar ...
	[SUCCESSFUL ] org.apache.commons#commons-compress;1.4.1!commons-compress.jar (111ms)
downloading https://repo1.maven.org/maven2/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar ...
	[SUCCESSFUL ] org.codehaus.jettison#jettison;1.1!jettison.jar(bundle) (66ms)
downloading https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar ...
	[SUCCESSFUL ] com.sun.xml.bind#jaxb-impl;2.2.3-1!jaxb-impl.jar (239ms)
downloading https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-jaxrs/1.9.13/jackson-jaxrs-1.9.13.jar ...
	[SUCCESSFUL ] org.codehaus.jackson#jackson-jaxrs;1.9.13!jackson-jaxrs.jar (54ms)
downloading https://repo1.maven.org/maven2/org/codehaus/jackson/jackson-xc/1.9.13/jackson-xc-1.9.13.jar ...
	[SUCCESSFUL ] org.codehaus.jackson#jackson-xc;1.9.13!jackson-xc.jar (57ms)
downloading https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar ...
	[SUCCESSFUL ] javax.xml.bind#jaxb-api;2.2.2!jaxb-api.jar (69ms)
downloading https://repo1.maven.org/maven2/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar ...
	[SUCCESSFUL ] javax.xml.stream#stax-api;1.0-2!stax-api.jar (67ms)
downloading https://repo1.maven.org/maven2/javax/activation/activation/1.1/activation-1.1.jar ...
	[SUCCESSFUL ] javax.activation#activation;1.1!activation.jar (62ms)
downloading https://repo1.maven.org/maven2/asm/asm/3.2/asm-3.2.jar ...
	[SUCCESSFUL ] asm#asm;3.2!asm.jar (65ms)
downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.jar ...
	[SUCCESSFUL ] org.apache.httpcomponents#httpclient;4.2.5!httpclient.jar (139ms)
downloading https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.2.5/httpcore-4.2.5.jar ...
	[SUCCESSFUL ] org.apache.httpcomponents#httpcore;4.2.5!httpcore.jar (114ms)
downloading https://repo1.maven.org/maven2/com/jamesmurty/utils/java-xmlbuilder/0.4/java-xmlbuilder-0.4.jar ...
	[SUCCESSFUL ] com.jamesmurty.utils#java-xmlbuilder;0.4!java-xmlbuilder.jar (53ms)
downloading https://repo1.maven.org/maven2/commons-digester/commons-digester/1.8/commons-digester-1.8.jar ...
	[SUCCESSFUL ] commons-digester#commons-digester;1.8!commons-digester.jar (77ms)
downloading https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar ...
	[SUCCESSFUL ] commons-beanutils#commons-beanutils-core;1.8.0!commons-beanutils-core.jar (89ms)
downloading https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar ...
	[SUCCESSFUL ] commons-beanutils#commons-beanutils;1.7.0!commons-beanutils.jar (93ms)
downloading https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar ...
	[SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.3!paranamer.jar (58ms)
downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.jar ...
	[SUCCESSFUL ] org.xerial.snappy#snappy-java;1.0.4.1!snappy-java.jar(bundle) (261ms)
downloading https://repo1.maven.org/maven2/org/tukaani/xz/1.0/xz-1.0.jar ...
	[SUCCESSFUL ] org.tukaani#xz;1.0!xz.jar (68ms)
downloading https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar ...
	[SUCCESSFUL ] org.apache.directory.server#apacheds-kerberos-codec;2.0.0-M15!apacheds-kerberos-codec.jar(bundle) (224ms)
downloading https://repo1.maven.org/maven2/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.jar ...
	[SUCCESSFUL ] org.apache.curator#curator-framework;2.7.1!curator-framework.jar(bundle) (85ms)
downloading https://repo1.maven.org/maven2/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar ...
	[SUCCESSFUL ] org.apache.directory.server#apacheds-i18n;2.0.0-M15!apacheds-i18n.jar(bundle) (61ms)
downloading https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar ...
	[SUCCESSFUL ] org.apache.directory.api#api-asn1-api;1.0.0-M20!api-asn1-api.jar(bundle) (64ms)
downloading https://repo1.maven.org/maven2/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar ...
	[SUCCESSFUL ] org.apache.directory.api#api-util;1.0.0-M20!api-util.jar(bundle) (67ms)
downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar ...
	[SUCCESSFUL ] org.slf4j#slf4j-log4j12;1.7.10!slf4j-log4j12.jar (60ms)
downloading https://repo1.maven.org/maven2/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.jar ...
	[SUCCESSFUL ] io.netty#netty;3.6.2.Final!netty.jar(bundle) (415ms)
downloading https://repo1.maven.org/maven2/javax/servlet/jsp/jsp-api/2.1/jsp-api-2.1.jar ...
	[SUCCESSFUL ] javax.servlet.jsp#jsp-api;2.1!jsp-api.jar (67ms)
downloading https://repo1.maven.org/maven2/jline/jline/0.9.94/jline-0.9.94.jar ...
	[SUCCESSFUL ] jline#jline;0.9.94!jline.jar (63ms)
downloading https://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.jar ...
	[SUCCESSFUL ] junit#junit;4.11!junit.jar (101ms)
downloading https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar ...
	[SUCCESSFUL ] org.hamcrest#hamcrest-core;1.3!hamcrest-core.jar (63ms)
downloading https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.2.3/jackson-core-2.2.3.jar ...
	[SUCCESSFUL ] com.fasterxml.jackson.core#jackson-core;2.2.3!jackson-core.jar (84ms)
downloading https://repo1.maven.org/maven2/joda-time/joda-time/2.10.13/joda-time-2.10.13.jar ...

	[SUCCESSFUL ] joda-time#joda-time;2.10.13!joda-time.jar (180ms)
:: resolution report :: resolve 54001ms :: artifacts dl 13166ms
	:: modules in use:
	asm#asm;3.2 from central in [default]
	com.amazonaws#aws-java-sdk;1.7.4 from central in [default]
	com.fasterxml.jackson.core#jackson-annotations;2.2.3 from central in [default]
	com.fasterxml.jackson.core#jackson-core;2.2.3 from central in [default]
	com.fasterxml.jackson.core#jackson-databind;2.2.3 from central in [default]
	com.google.code.findbugs#jsr305;3.0.0 from central in [default]
	com.google.code.gson#gson;2.2.4 from central in [default]
	com.google.guava#guava;11.0.2 from central in [default]
	com.google.protobuf#protobuf-java;2.5.0 from central in [default]
	com.jamesmurty.utils#java-xmlbuilder;0.4 from central in [default]
	com.jcraft#jsch;0.1.42 from central in [default]
	com.sun.jersey#jersey-core;1.9 from central in [default]
	com.sun.jersey#jersey-json;1.9 from central in [default]
	com.sun.jersey#jersey-server;1.9 from central in [default]
	com.sun.xml.bind#jaxb-impl;2.2.3-1 from central in [default]
	com.thoughtworks.paranamer#paranamer;2.3 from central in [default]
	commons-beanutils#commons-beanutils;1.7.0 from central in [default]
	commons-beanutils#commons-beanutils-core;1.8.0 from central in [default]
	commons-cli#commons-cli;1.2 from central in [default]
	commons-codec#commons-codec;1.4 from central in [default]
	commons-collections#commons-collections;3.2.1 from central in [default]
	commons-configuration#commons-configuration;1.6 from central in [default]
	commons-digester#commons-digester;1.8 from central in [default]
	commons-httpclient#commons-httpclient;3.1 from central in [default]
	commons-io#commons-io;2.4 from central in [default]
	commons-lang#commons-lang;2.6 from central in [default]
	commons-logging#commons-logging;1.1.3 from central in [default]
	commons-net#commons-net;3.1 from central in [default]
	io.netty#netty;3.6.2.Final from central in [default]
	javax.activation#activation;1.1 from central in [default]
	javax.servlet#servlet-api;2.5 from central in [default]
	javax.servlet.jsp#jsp-api;2.1 from central in [default]
	javax.xml.bind#jaxb-api;2.2.2 from central in [default]
	javax.xml.stream#stax-api;1.0-2 from central in [default]
	jline#jline;0.9.94 from central in [default]
	joda-time#joda-time;2.10.13 from central in [default]
	junit#junit;4.11 from central in [default]
	log4j#log4j;1.2.17 from central in [default]
	net.java.dev.jets3t#jets3t;0.9.0 from central in [default]
	org.apache.avro#avro;1.7.4 from central in [default]
	org.apache.commons#commons-compress;1.4.1 from central in [default]
	org.apache.commons#commons-math3;3.1.1 from central in [default]
	org.apache.curator#curator-client;2.7.1 from central in [default]
	org.apache.curator#curator-framework;2.7.1 from central in [default]
	org.apache.curator#curator-recipes;2.7.1 from central in [default]
	org.apache.directory.api#api-asn1-api;1.0.0-M20 from central in [default]
	org.apache.directory.api#api-util;1.0.0-M20 from central in [default]
	org.apache.directory.server#apacheds-i18n;2.0.0-M15 from central in [default]
	org.apache.directory.server#apacheds-kerberos-codec;2.0.0-M15 from central in [default]
	org.apache.hadoop#hadoop-annotations;2.7.0 from central in [default]
	org.apache.hadoop#hadoop-auth;2.7.0 from central in [default]
	org.apache.hadoop#hadoop-aws;2.7.0 from central in [default]
	org.apache.hadoop#hadoop-common;2.7.0 from central in [default]
	org.apache.htrace#htrace-core;3.1.0-incubating from central in [default]
	org.apache.httpcomponents#httpclient;4.2.5 from central in [default]
	org.apache.httpcomponents#httpcore;4.2.5 from central in [default]
	org.apache.zookeeper#zookeeper;3.4.6 from central in [default]
	org.codehaus.jackson#jackson-core-asl;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-jaxrs;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-mapper-asl;1.9.13 from central in [default]
	org.codehaus.jackson#jackson-xc;1.9.13 from central in [default]
	org.codehaus.jettison#jettison;1.1 from central in [default]
	org.hamcrest#hamcrest-core;1.3 from central in [default]
	org.mortbay.jetty#jetty;6.1.26 from central in [default]
	org.mortbay.jetty#jetty-util;6.1.26 from central in [default]
	org.slf4j#slf4j-api;1.7.10 from central in [default]
	org.slf4j#slf4j-log4j12;1.7.10 from central in [default]
	org.tukaani#xz;1.0 from central in [default]
	org.xerial.snappy#snappy-java;1.0.4.1 from central in [default]
	xmlenc#xmlenc;0.52 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   70  |   70  |   70  |   0   ||   70  |   70  |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-f9647eea-c67e-4203-a5fa-ab641bcec7a2
	confs: [default]
	70 artifacts copied, 0 already retrieved (36369kB/504ms)
21/12/11 13:30:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

### Process Song data

In [129]:
songdf = spark.read.json("s3a://udacity-dend/song_data/*/*/*")

21/12/12 17:07:50 WARN FileSystem: Failed to initialize fileystem s3a://udacity-dend/song_data/*/*/*: java.lang.NumberFormatException: For input string: "64M"
21/12/12 17:07:50 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://udacity-dend/song_data/*/*/*.
java.lang.NumberFormatException: For input string: "64M"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Long.parseLong(Long.java:707)
	at java.base/java.lang.Long.parseLong(Long.java:832)
	at org.apache.hadoop.conf.Configuration.getLong(Configuration.java:1565)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:248)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:405)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:832)
21/12/12 17:07:50 WARN FileSystem: Failed to initialize fileystem s3a://udacity-dend/song_data/*/*/*: java.lang.NumberFormatException: For input string: "64M"

Py4JJavaError: An error occurred while calling o1608.json.
: java.lang.NumberFormatException: For input string: "64M"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Long.parseLong(Long.java:707)
	at java.base/java.lang.Long.parseLong(Long.java:832)
	at org.apache.hadoop.conf.Configuration.getLong(Configuration.java:1565)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:248)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:747)
	at scala.collection.immutable.List.map(List.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:745)
	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:577)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:274)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:245)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:405)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:832)

In [8]:
songdf.printSchema()

root
 |-- artist_id: string (nullable = true)
 |-- artist_latitude: double (nullable = true)
 |-- artist_location: string (nullable = true)
 |-- artist_longitude: double (nullable = true)
 |-- artist_name: string (nullable = true)
 |-- duration: double (nullable = true)
 |-- num_songs: long (nullable = true)
 |-- song_id: string (nullable = true)
 |-- title: string (nullable = true)
 |-- year: long (nullable = true)

In [17]:
songdf.limit(5).toPandas()

,artist_id,artist_latitude,artist_location,artist_longitude,artist_name,duration,num_songs,song_id,title,year
0,ARDR4AC1187FB371A1,NaN,,NaN,Montserrat Caballé;Placido Domingo;Vicente Sar...,511.16363,1,SOBAYLL12A8C138AF9,Sono andati? Fingevo di dormire,0
1,AREBBGV1187FB523D2,NaN,"Houston, TX",NaN,Mike Jones (Featuring CJ_ Mello & Lil' Bran),173.66159,1,SOOLYAZ12A6701F4A6,Laws Patrolling (Album Version),0
2,ARMAC4T1187FB3FA4C,40.82624,"Morris Plains, NJ",-74.47995,The Dillinger Escape Plan,207.77751,1,SOBBUGU12A8C13E95D,Setting Fire to Sleeping Giants,2004
3,ARPBNLO1187FB3D52F,40.71455,"New York, NY",-74.00712,Tiny Tim,43.36281,1,SOAOIBZ12AB01815BE,I Hold Your Hand In Mine [Live At Royal Albert...,2000
4,ARDNS031187B9924F0,32.67828,Georgia,-83.22295,Tim Wilson,186.48771,1,SONYPOM12A8C13B2D7,I Think My Wife Is Running Around On Me (Taco ...,2005

In [34]:
songdf = songdf.withColumn("year", col("year").cast(IntegerType())) \
    .withColumn("num_songs", col("num_songs").cast(IntegerType()))

In [36]:
songdf.printSchema()

root
 |-- artist_id: string (nullable = true)
 |-- artist_latitude: double (nullable = true)
 |-- artist_location: string (nullable = true)
 |-- artist_longitude: double (nullable = true)
 |-- artist_name: string (nullable = true)
 |-- duration: double (nullable = true)
 |-- num_songs: integer (nullable = true)
 |-- song_id: string (nullable = true)
 |-- title: string (nullable = true)
 |-- year: integer (nullable = true)

In [51]:
# Create songs table
songs_table = songdf.filter(col("song_id").isNotNull()) \
    .select("song_id", "title", "artist_id", "year", "duration") \
    .drop_duplicates(["song_id"])
songs_table.limit(5).toPandas()

,song_id,title,artist_id,year,duration
0,SOAOIBZ12AB01815BE,I Hold Your Hand In Mine [Live At Royal Albert...,ARPBNLO1187FB3D52F,2000,43.36281
1,SOBAYLL12A8C138AF9,Sono andati? Fingevo di dormire,ARDR4AC1187FB371A1,0,511.16363
2,SOBBUGU12A8C13E95D,Setting Fire to Sleeping Giants,ARMAC4T1187FB3FA4C,2004,207.77751
3,SOBBXLX12A58A79DDA,Erica (2005 Digital Remaster),AREDBBQ1187B98AFF5,0,138.63138
4,SOBCOSW12A8C13D398,Rumba De Barcelona,AR7SMBG1187B9B9066,0,218.38322

In [130]:
songs_table.limit(5).show()

+------------------+--------------------+------------------+----+---------+
|           song_id|               title|         artist_id|year| duration|
+------------------+--------------------+------------------+----+---------+
|SOAOIBZ12AB01815BE|I Hold Your Hand ...|ARPBNLO1187FB3D52F|2000| 43.36281|
|SOBAYLL12A8C138AF9|Sono andati? Fing...|ARDR4AC1187FB371A1|   0|511.16363|
|SOBBUGU12A8C13E95D|Setting Fire to S...|ARMAC4T1187FB3FA4C|2004|207.77751|
|SOBBXLX12A58A79DDA|Erica (2005 Digit...|AREDBBQ1187B98AFF5|   0|138.63138|
|SOBCOSW12A8C13D398|  Rumba De Barcelona|AR7SMBG1187B9B9066|   0|218.38322|
+------------------+--------------------+------------------+----+---------+

In [39]:
# Save into parquet
songs_table.write.partitionBy("year", "artist_id").parquet("songs_table")

In [50]:
# Create artists table
artists_table = songdf.filter(col("artist_id").isNotNull()) \
    .select("artist_id", "artist_name", "artist_location", "artist_latitude", "artist_longitude") \
    .drop_duplicates(["artist_id"])
artists_table.limit(5).toPandas()

,artist_id,artist_name,artist_location,artist_latitude,artist_longitude
0,AR051KA1187B98B2FF,Wilks,,NaN,NaN
1,AR0IAWL1187B9A96D0,Danilo Perez,Panama,8.41770,-80.11278
2,AR0RCMP1187FB3F427,Billie Jo Spears,"Beaumont, TX",30.08615,-94.10158
3,AR10USD1187B99F3F1,Tweeterfriendly Music,"Burlington, Ontario, Canada",NaN,NaN
4,AR1Y2PT1187FB5B9CE,John Wesley,Brandon,27.94017,-82.32547

In [41]:
# Save into parquet
artists_table.write.parquet("artists_table")

### Process Log data

In [74]:
logdf = spark.read.json("log-data/*")

In [75]:
logdf.printSchema()

root
 |-- artist: string (nullable = true)
 |-- auth: string (nullable = true)
 |-- firstName: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- itemInSession: long (nullable = true)
 |-- lastName: string (nullable = true)
 |-- length: double (nullable = true)
 |-- level: string (nullable = true)
 |-- location: string (nullable = true)
 |-- method: string (nullable = true)
 |-- page: string (nullable = true)
 |-- registration: double (nullable = true)
 |-- sessionId: long (nullable = true)
 |-- song: string (nullable = true)
 |-- status: long (nullable = true)
 |-- ts: long (nullable = true)
 |-- userAgent: string (nullable = true)
 |-- userId: string (nullable = true)

In [76]:
logdf.limit(5).toPandas()

,artist,auth,firstName,gender,itemInSession,lastName,length,level,location,method,page,registration,sessionId,song,status,ts,userAgent,userId
0,Harmonia,Logged In,Ryan,M,0,Smith,655.77751,free,"San Jose-Sunnyvale-Santa Clara, CA",PUT,NextSong,1.541017e+12,583,Sehr kosmisch,200,1542241826796,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",26
1,The Prodigy,Logged In,Ryan,M,1,Smith,260.07465,free,"San Jose-Sunnyvale-Santa Clara, CA",PUT,NextSong,1.541017e+12,583,The Big Gundown,200,1542242481796,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",26
2,Train,Logged In,Ryan,M,2,Smith,205.45261,free,"San Jose-Sunnyvale-Santa Clara, CA",PUT,NextSong,1.541017e+12,583,Marry Me,200,1542242741796,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",26
3,None,Logged In,Wyatt,M,0,Scott,NaN,free,"Eureka-Arcata-Fortuna, CA",GET,Home,1.540872e+12,563,None,200,1542247071796,Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7....,9
4,None,Logged In,Austin,M,0,Rosales,NaN,free,"New York-Newark-Jersey City, NY-NJ-PA",GET,Home,1.541060e+12,521,None,200,1542252577796,Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20...,12

In [77]:
logdf = logdf.withColumn("itemInSession", col("itemInSession").cast(IntegerType())).withColumn("userId", col("userId").cast(IntegerType()))

In [78]:
logdf.printSchema()

root
 |-- artist: string (nullable = true)
 |-- auth: string (nullable = true)
 |-- firstName: string (nullable = true)
 |-- gender: string (nullable = true)
 |-- itemInSession: integer (nullable = true)
 |-- lastName: string (nullable = true)
 |-- length: double (nullable = true)
 |-- level: string (nullable = true)
 |-- location: string (nullable = true)
 |-- method: string (nullable = true)
 |-- page: string (nullable = true)
 |-- registration: double (nullable = true)
 |-- sessionId: long (nullable = true)
 |-- song: string (nullable = true)
 |-- status: long (nullable = true)
 |-- ts: long (nullable = true)
 |-- userAgent: string (nullable = true)
 |-- userId: integer (nullable = true)

In [79]:
# Create users table
users_table = logdf.filter(col("userId").isNotNull()) \
    .select("userId", "firstName", "lastName", "gender", "level") \
    .drop_duplicates(["userId"])

In [49]:
users_table.limit(5).toPandas()

   userId firstName  lastName gender level
0       2   Jizelle  Benjamin      F  free
1       3     Isaac    Valdez      M  free
2       4    Alivia   Terrell      F  free
3       5    Elijah     Davis      M  free
4       6   Cecilia     Owens      F  free

In [81]:
users_table.write.parquet("users_table")

In [82]:
# Create timestamp column from original timestamp column
@udf(TimestampType())
def to_timestamp(ts):
    timestamp = datetime.fromtimestamp(ts // 1000)
    return timestamp

logdf = logdf.withColumn("timestamp", to_timestamp("ts"))

In [83]:
logdf.limit(5).toPandas()

,artist,auth,firstName,gender,itemInSession,lastName,length,level,location,method,page,registration,sessionId,song,status,ts,userAgent,userId,timestamp
0,Harmonia,Logged In,Ryan,M,0,Smith,655.77751,free,"San Jose-Sunnyvale-Santa Clara, CA",PUT,NextSong,1.541017e+12,583,Sehr kosmisch,200,1542241826796,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",26,2018-11-14 18:30:26
1,The Prodigy,Logged In,Ryan,M,1,Smith,260.07465,free,"San Jose-Sunnyvale-Santa Clara, CA",PUT,NextSong,1.541017e+12,583,The Big Gundown,200,1542242481796,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",26,2018-11-14 18:41:21
2,Train,Logged In,Ryan,M,2,Smith,205.45261,free,"San Jose-Sunnyvale-Santa Clara, CA",PUT,NextSong,1.541017e+12,583,Marry Me,200,1542242741796,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",26,2018-11-14 18:45:41
3,None,Logged In,Wyatt,M,0,Scott,NaN,free,"Eureka-Arcata-Fortuna, CA",GET,Home,1.540872e+12,563,None,200,1542247071796,Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7....,9,2018-11-14 19:57:51
4,None,Logged In,Austin,M,0,Rosales,NaN,free,"New York-Newark-Jersey City, NY-NJ-PA",GET,Home,1.541060e+12,521,None,200,1542252577796,Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20...,12,2018-11-14 21:29:37

In [98]:
# Create datetime column from timestamp column
@udf(DateType())
def to_datetime(ts):
    dt = datetime.fromtimestamp(ts // 1000)
    return dt
logdf = logdf.withColumn("dt", to_datetime("ts"))

In [99]:
logdf.limit(5).toPandas()

,artist,auth,firstName,gender,itemInSession,lastName,length,level,location,method,page,registration,sessionId,song,status,ts,userAgent,userId,timestamp,dt
0,Harmonia,Logged In,Ryan,M,0,Smith,655.77751,free,"San Jose-Sunnyvale-Santa Clara, CA",PUT,NextSong,1.541017e+12,583,Sehr kosmisch,200,1542241826796,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",26,2018-11-14 18:30:26,2018-11-14
1,The Prodigy,Logged In,Ryan,M,1,Smith,260.07465,free,"San Jose-Sunnyvale-Santa Clara, CA",PUT,NextSong,1.541017e+12,583,The Big Gundown,200,1542242481796,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",26,2018-11-14 18:41:21,2018-11-14
2,Train,Logged In,Ryan,M,2,Smith,205.45261,free,"San Jose-Sunnyvale-Santa Clara, CA",PUT,NextSong,1.541017e+12,583,Marry Me,200,1542242741796,"""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5...",26,2018-11-14 18:45:41,2018-11-14
3,None,Logged In,Wyatt,M,0,Scott,NaN,free,"Eureka-Arcata-Fortuna, CA",GET,Home,1.540872e+12,563,None,200,1542247071796,Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7....,9,2018-11-14 19:57:51,2018-11-14
4,None,Logged In,Austin,M,0,Rosales,NaN,free,"New York-Newark-Jersey City, NY-NJ-PA",GET,Home,1.541060e+12,521,None,200,1542252577796,Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20...,12,2018-11-14 21:29:37,2018-11-14

In [110]:
year = udf(lambda x: x.year, IntegerType())
month = udf(lambda x: x.month, IntegerType())
day = udf(lambda x: x.day, IntegerType())
week = udf(lambda x: x.isocalendar()[1], IntegerType())
hour = udf(lambda x: x.hour, IntegerType())
weekday = udf(lambda x: x.weekday(), IntegerType()

In [113]:
# Create time table
time_table = logdf.withColumn("year", year("timestamp")) \
    .withColumn("month", month("timestamp")) \
    .withColumn("day", day("timestamp")) \
    .withColumn("week", week("timestamp")) \
    .withColumn("hour", hour("timestamp")) \
    .withColumn("weekday", weekday("timestamp")) \
    .selectExpr("ts AS start_time", "hour", "day", "week", "month", "year", "weekday").drop_duplicates(["start_time"])

In [114]:
time_table.limit(5).toPandas()

      start_time  hour  day  week  month  year  weekday
0  1542795222796     4   21    47     11  2018        2
1  1542798065796     5   21    47     11  2018        2
2  1542825241796    12   21    47     11  2018        2
3  1542833066796    14   21    47     11  2018        2
4  1542166672796    21   13    46     11  2018        1

In [115]:
time_table.write.partitionBy("year", "month").parquet("time_table")

In [124]:
cond1 = [logdf.song == songs_table.title]
songslogs = logdf.join(songs_table, cond) \
    .withColumn("songplay_id", monotonically_increasing_id()) \
    .selectExpr("ts AS start_time", "userId", "level", "song_id", "artist_id", "sessionId", "location", "userAgent")
songslogs.sort("userId").toPandas()

,start_time,userId,level,song_id,artist_id,sessionId,location,userAgent
0,1542171963796,10,free,SOGDBUF12A8C140FAA,AR558FS1187FB45658,484,"Washington-Arlington-Alexandria, DC-VA-MD-WV","""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4..."
1,1542837407796,15,paid,SOZCTXZ12AB0182364,AR5KOSW1187FB35FF4,818,"Chicago-Naperville-Elgin, IL-IN-WI","""Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/5..."
2,1542618860796,24,paid,SOGDBUF12A8C140FAA,AR558FS1187FB45658,672,"Lake Havasu City-Kingman, AZ","""Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebK..."
3,1543358159796,80,paid,SOGDBUF12A8C140FAA,AR558FS1187FB45658,992,"Portland-South Portland, ME","""Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4..."

In [125]:
songsplays = songslogs.withColumn("dt", to_datetime("start_time")).withColumn("year", year("dt")).withColumn("month", month("dt"))

In [128]:
songsplays.write.partitionBy("year", "month").parquet("songplays_table")